### ISSUE TITLE
Error using HtmlProvider in Blazor/Bolero

### ISSUE THREAD

**Issue by sandeepc24** [fsprojects/FSharp.Data#1390] opened 2021-08-20 10:40 UTC
I get error ```System.Net.Requests is not supported on this platform.``` when using HtmlProvider in Bolero app.

**Comment by cartermp** [comment] 2021-09-08 21:29
Closing as a duplicate of https://github.com/fsprojects/FSharp.Data/issues/1392

**Closed by cartermp** 2021-09-08 21:29 UTC
